stages:
  filter:
    cmd: python3 src/filter.py
    deps:
    - data/data.csv
    - src/filter.py
    params:
    - parameters/params.yaml:
      - filter.value
    outs:
    - output/filter
  training:
    cmd: python3 src/training.py output/filter
    deps:
    - output/filter
    - src/training.py
    params:
    - parameters/params.yaml:
      - training.num_rows
    outs:
    - output/training
