stages:
  filter:
    cmd: python3 filter.py
    deps:
    - filter.py
    - regression-data/regression_data.csv
    params:
    - filter.value
    outs:
    - output/filter
  training:
    cmd: python3 training.py output/filter
    deps:
    - output/filter
    - regression-data/regression_data.csv
    - training.py
    params:
    - training.num_rows
    outs:
    - output/training
